### DISCUSSION TITLE
Unwrapping object in custom serializer

### DISCUSSION THREAD

**Discussion by micsport13** [FasterXML/jackson-databind#4637] [Q&A]
Due to some various factors and the complicated class structure I have, I need to use custom serialization rather than the default annotation based approach.  I was wondering if there's any guides or specific methods I'm missing in order to unwrap a value within the object context.  For context, here's my code:
```
public class ConstantValueGeneratorSerializer extends JsonSerializer<ConstantValueGenerator> {

  @Override
  public void serialize(
      ConstantValueGenerator constantValueGenerator,
      JsonGenerator jsonGenerator,
      SerializerProvider serializerProvider)
      throws IOException {
    String aliasName =
        Primitives.getAliasFromWrapperClass(constantValueGenerator.getConstantValue().getClass());
    Primitives primitives = Primitives.fromString(aliasName);
    jsonGenerator.writeObjectFieldStart("value");
    jsonGenerator.writeStringField("type", aliasName);
    jsonGenerator.writeFieldName("value"); // FIXME: Figure out how to unwrap this value
    switch (primitives) {
      case CUSTOM -> jsonGenerator.writeObject(constantValueGenerator.getConstantValue());
      case INT, DOUBLE, FLOAT, SHORT, BYTE, BOOLEAN, CHAR ->
          jsonGenerator.writeObject(
              Primitives.parseSimpleValueFromString(
                  primitives, constantValueGenerator.getConstantValue().toString()));
      default -> throw new IllegalArgumentException("Invalid primitive type");
    }
    jsonGenerator.writeEndObject();
  }

  @Override
  public void serializeWithType(
      ConstantValueGenerator value,
      JsonGenerator gen,
      SerializerProvider provider,
      TypeSerializer typeSerializer)
      throws IOException {
    WritableTypeId typeId = typeSerializer.typeId(value, JsonToken.START_OBJECT);
    typeSerializer.writeTypePrefix(gen, typeId);
    serialize(value, gen, provider);
    typeSerializer.writeTypeSuffix(gen, typeId);
  }
```
The problem arises on the `jsonGenerator.writeObject(...` line which works because I have wrapped the value by writing a field name but I was wondering, is it possible to unwrap that value and simply write the object within the value field name above?

It currently results in:
```
  value:
    type: custom
    value:
      class_name: java.time.Period
      method_name: of
      method_args:
        - type: int
          value: 0
        - type: int
          value: 0
        - type: int
          value: 1
```
but I would like
```
  value:
    type: custom
    class_name: java.time.Period
    method_name: of
    method_args:
      - type: int
        value: 0
      - type: int
        value: 0
      - type: int
        value: 1
```
Is this possible in a custom serializer?
